/**
 * NEXUS COGNITIVE SUPREMACY — COMPLETE UNIVERSAL MENTAL DATABASE
 * TIER 0 → TIER 9 · ALL documented cognitive abilities
 * Social · Emotional · Moral · Spatial · Temporal · Security · BCI · Archetypes
 */

(function() {
const COGNITIVE_SUPREMACY = [

// ══════════════════════════════════════════════════════════════════
// TIER 0 — PRIME COGNITIVE ENGINE
// ══════════════════════════════════════════════════════════════════
{g:'⚡ TIER 0 · PRIME COGNITIVE ENGINE',s:[
  'Working memory expansion (7±2 → 15+ chunks)',
  'Cognitive flexibility (task-switch in <100ms)',
  'Inhibitory control (block irrelevant info perfectly)',
  'Fluid intelligence (solve novel problems instantly)',
  'Crystallized intelligence (vast encoded knowledge)',
  'Processing speed (pattern match at machine rate)',
  'Divided attention (true parallel track processing)',
  'Sustained attention (hours of focused laser clarity)',
  'Selective attention (filter signal from noise 99.9%)',
  'Executive function (plan→sequence→execute flawlessly)',
  'Metacognition (think about thinking recursively)',
  'Cognitive load management (never overloaded)',
  'Mental bandwidth allocation (dynamic resource routing)',
  'Prefrontal cortex dominance (override emotion→logic)',
  'Default mode network control (silence rumination)',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 1 — REASONING & LOGIC
// ══════════════════════════════════════════════════════════════════
{g:'TIER 1 · DEDUCTIVE REASONING',s:[
  'Formal logic (propositional · predicate · modal)',
  'Syllogistic reasoning','Modus ponens / modus tollens',
  'Reductio ad absurdum','Proof by contradiction',
  'Mathematical induction','Transitive closure',
  'Boolean algebra','Truth table construction',
  'Valid vs sound argument distinction',
  'Necessary vs sufficient conditions',
  'Logical equivalence detection','Paradox resolution',
  'Formal proofs (Lean / Coq / Isabelle level)',
  'Type theory reasoning','Category theory thinking',
]},
{g:'TIER 1 · INDUCTIVE REASONING',s:[
  'Pattern extrapolation from minimal data',
  'Statistical induction','Enumerative induction',
  'Eliminative induction (Mill\'s methods)',
  'Analogical induction','Causal induction',
  'Bayesian updating (real-time belief revision)',
  'Hypothesis generation from observations',
  'Regularization of noisy patterns',
  'Signal vs noise discrimination',
  'Overfitting detection in reasoning',
  'Generalization boundary setting',
  'Sample size intuition','Selection bias detection',
]},
{g:'TIER 1 · ABDUCTIVE REASONING',s:[
  'Inference to best explanation (IBE)',
  'Minimum description length principle',
  'Occam\'s razor application','Peirce\'s abduction',
  'Diagnostic reasoning (symptom→cause)',
  'Retroductive analysis','Constraint satisfaction',
  'Most probable explanation ranking',
  'Evidence weighing under uncertainty',
  'Bayesian hypothesis ranking',
  'Prior probability calibration',
  'Likelihood ratio computation',
  'Eliminative logic','Sherlock-mode deduction',
]},
{g:'TIER 1 · COUNTERFACTUAL REASONING',s:[
  'If-X-then-Y invariance testing',
  'Minimal counterfactual world construction',
  'Possible worlds semantics','Causal counterfactuals (do-calculus)',
  'Subjunctive conditionals','Backtracking counterfactuals',
  'Regret minimization via counterfactual simulation',
  'Alternative history modeling','Near-miss analysis',
  'Decision tree backward induction',
  'Structural equation model inference',
  'Intervention vs observation logic',
  'Counterfactual fairness reasoning',
]},
{g:'TIER 1 · CAUSAL REASONING',s:[
  'Directed acyclic graph (DAG) construction',
  'Confounding identification','Instrumental variable reasoning',
  'Front-door / back-door criteria (Pearl)',
  'Mediation analysis','Moderation analysis',
  'Randomization logic','Natural experiment identification',
  'Difference-in-differences thinking',
  'Regression discontinuity intuition',
  'Granger causality','Structural causal models',
  'Counterfactual causation','INUS conditions',
  'Root cause chain tracing',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 2 — ADVANCED COGNITIVE ARCHITECTURES
// ══════════════════════════════════════════════════════════════════
{g:'TIER 2 · SYSTEMS THINKING',s:[
  'Feedback loop identification (reinforcing/balancing)',
  'Stock-and-flow modeling','Leverage point finding (Meadows)',
  'Mental model construction','Dynamic complexity navigation',
  'Emergence detection','Self-organization recognition',
  'Non-linear dynamics intuition','Tipping point prediction',
  'Regime shift detection','Resilience analysis',
  'Complexity vs complicatedness distinction',
  'Wicked problem framing','Second-order effects projection',
  'Nth-order consequence chains','Unintended consequence modeling',
]},
{g:'TIER 2 · STRATEGIC INTELLIGENCE',s:[
  'Multi-level strategic thinking (tactical/operational/grand)',
  'Game theory (Nash equilibrium · Pareto · Schelling)',
  'Zero-sum vs positive-sum detection',
  'Information asymmetry exploitation',
  'Opponent modeling','Theory of mind (5+ levels deep)',
  'Pre-mortem analysis','Red team / blue team switching',
  'Scenario planning','Wargaming','Decision trees',
  'Expected value computation under uncertainty',
  'Option value preservation','Real options thinking',
  'Irreversibility weighting','Commitment device design',
]},
{g:'TIER 2 · PATTERN RECOGNITION',s:[
  'Visual pattern recognition (expert-level)',
  'Temporal pattern recognition',
  'Structural isomorphism detection across domains',
  'Semantic pattern matching','Syntactic pattern matching',
  'Statistical pattern recognition',
  'Anomaly detection (sigma-level precision)',
  'Compression as intelligence (Kolmogorov complexity)',
  'Chunking (expert perceptual chunks)',
  'Schema-driven recognition','Prototype matching',
  'Exemplar matching','Feature conjunction search',
  'Spatial pattern recognition','Network pattern recognition',
]},
{g:'TIER 2 · MEMORY ARCHITECTURE',s:[
  'Episodic memory (precise event recall with context)',
  'Semantic memory (vast encyclopedic knowledge)',
  'Procedural memory (skill transfer across domains)',
  'Prospective memory (future-action scheduling)',
  'Working memory + long-term memory bridging',
  'Method of loci (memory palace mastery)',
  'Chunking for compression','Spaced repetition encoding',
  'Active recall testing','Interleaved practice',
  'Dual coding (verbal + visual simultaneously)',
  'Elaborative interrogation','Self-explanation',
  'Sleep consolidation optimization',
  'Retrieval cue design','Associative network construction',
]},
{g:'TIER 2 · ABSTRACT THINKING',s:[
  'Conceptual abstraction (extract essence instantly)',
  'Mathematical abstraction','Structural abstraction',
  'Ontology construction','Concept formation',
  'Category learning','Prototype construction',
  'Analogy generation','Cross-domain mapping',
  'Metaphor creation and interpretation',
  'Symbol manipulation','Formal system navigation',
  'Algebraic thinking','Topological intuition',
  'Functional abstraction','λ-calculus thinking',
]},
{g:'TIER 2 · CREATIVE INTELLIGENCE',s:[
  'Divergent thinking (TTCT-level fluency)',
  'Convergent synthesis (optimal selection from many)',
  'Remote associate linking','Combinatorial creativity',
  'Conceptual blending (Fauconnier & Turner)',
  'Bisociation (Koestler)','SCAMPER methodology',
  'Lateral thinking (de Bono)','Random stimulus entry',
  'Constraint-based creativity','Oblique strategies',
  'Analogical transfer across domains',
  'Novel problem formulation','Reframing','Perspective shift',
  'Incubation (unconscious processing)',
  'Creative flow state induction',
]},
{g:'TIER 2 · LANGUAGE & SYMBOLIC COGNITION',s:[
  'Natural language parsing (deep structural)',
  'Ambiguity resolution','Pragmatic inference',
  'Implicature detection','Presupposition identification',
  'Discourse coherence tracking',
  'Narrative comprehension and generation',
  'Frame problem navigation','Symbol grounding',
  'Conceptual metaphor comprehension',
  'Multi-lingual switching (cognitive cost near-zero)',
  'Formal language parsing (CFG/regex/PDA)',
  'Code reading fluency','Semantic role labeling',
  'Information extraction from dense text',
  'Summarization with compression control',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 3 — META-COGNITIVE SUPREMACY
// ══════════════════════════════════════════════════════════════════
{g:'TIER 3 · METACOGNITION',s:[
  'Thinking about thinking (recursive self-model)',
  'Calibration (know what you know / don\'t know)',
  'Epistemic humility without epistemic cowardice',
  'Dunning-Kruger immunity',
  'Knowledge boundary detection',
  'Confidence interval generation for beliefs',
  'Bias detection in own reasoning',
  'Cognitive blind spot identification',
  'Mental model auditing','Schema revision',
  'Belief update triggers','Intellectual honesty',
  'Second-order beliefs (belief about beliefs)',
  'Reflective equilibrium','Wide reflective equilibrium',
  'Self-explanation monitoring',
  'Metacognitive sensitivity (d-prime for errors)',
  'Type 2 signal detection (Maniscalco & Lau)',
  'Feeling-of-knowing accuracy calibration',
  'Source monitoring (where did I learn this?)',
  'Reality monitoring (did I do it or imagine it?)',
]},
{g:'TIER 3 · COGNITIVE BIAS IMMUNITY',s:[
  'Confirmation bias cancellation',
  'Anchoring resistance','Availability heuristic override',
  'Representativeness correction',
  'Base rate neglect prevention',
  'Hindsight bias elimination',
  'Overconfidence calibration',
  'Framing effect detection',
  'Sunk cost fallacy immunity',
  'Planning fallacy correction (×2.5 rule)',
  'Optimism bias adjustment',
  'Attribution error correction (FAE)',
  'In-group / out-group bias awareness',
  'Status quo bias resistance',
  'Narrative fallacy detection',
  'Conjunction fallacy immunity',
  'Gambler\'s fallacy immunity',
  'Hot-hand fallacy detection',
  'Scope insensitivity correction',
  'Affect heuristic override',
]},
{g:'TIER 3 · EPISTEMIC VIRTUE',s:[
  'Intellectual curiosity (drives exploration)',
  'Intellectual courage (defend unpopular truths)',
  'Intellectual humility (update on evidence)',
  'Open-mindedness (steelman before rebuttal)',
  'Impartiality (no motivated reasoning)',
  'Thoroughness (edge cases always checked)',
  'Intellectual empathy (inhabit other frameworks)',
  'Autonomy (reason independently from social pressure)',
  'Wonder (never stop asking why)',
  'Precision (exact language, no weasel words)',
  'Honesty (factual accuracy above all)',
  'Consistency (same standards for all claims)',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 4 — AI COGNITIVE ARCHITECTURES
// ══════════════════════════════════════════════════════════════════
{g:'TIER 4 · AI REASONING MODES',s:[
  'Chain-of-thought (sequential step reasoning)',
  'Tree of thoughts (branch + prune + select)',
  'Graph of thoughts (non-linear reasoning web)',
  'Reflexion (self-critique → revision loop)',
  'ReAct (Reason + Act interleaved)',
  'Debate (self-opposition → synthesis)',
  'Self-consistency (multi-path voting)',
  'Least-to-most prompting (decompose→solve→build)',
  'Step-back abstraction (generalize before specialize)',
  'Analogical prompting (few-shot analogy transfer)',
  'Program-of-thought (code as reasoning medium)',
  'Multimodal chain-of-thought',
  'Verification chain',
  'Constitutional AI (principle-guided self-correction)',
  'Process reward modeling',
]},
{g:'TIER 4 · COGNITIVE CONTROL SYSTEMS',s:[
  'Goal maintenance under distraction',
  'Task switching (minimal cost)',
  'Dual-task performance optimization',
  'Cognitive resource allocation',
  'Priority queuing (mental task stack)',
  'Interrupt handling (context save + restore)',
  'Error detection and correction in real-time',
  'Performance monitoring','Proactive interference management',
  'Retroactive interference management',
  'Attention to action (schema activation)',
  'Automaticity induction','Skill compilation',
  'Controlled vs automatic process routing',
  'Mental set shifting',
]},
{g:'TIER 4 · DECISION INTELLIGENCE',s:[
  'Expected utility maximization',
  'Multi-attribute utility theory',
  'Prospect theory correction (loss aversion awareness)',
  'Risk preference calibration',
  'Ambiguity vs risk distinction (Ellsberg)',
  'Decision under deep uncertainty (Maximin/MiniMax regret)',
  'Info value calculation (EVPI/EVSI)',
  'Sequential decision making (Bellman)',
  'Satisficing vs optimizing calibration',
  'Reversibility-weighted decisions',
  'Option value preservation',
  'Commitment effects',
  'Precommitment devices',
  'Two-system arbitration (fast vs slow)',
  'Pre-mortem cognitive override',
]},
{g:'TIER 4 · ALL INTELLIGENCE TYPES',s:[
  'Logical-mathematical intelligence',
  'Linguistic intelligence','Spatial intelligence',
  'Musical intelligence','Bodily-kinesthetic intelligence',
  'Interpersonal intelligence (read others)',
  'Intrapersonal intelligence (read self)',
  'Naturalist intelligence','Existential intelligence',
  'Fluid intelligence (novel problem solving)',
  'Crystallized intelligence (knowledge application)',
  'Visual-spatial reasoning (mental rotation)',
  'Auditory processing intelligence',
  'Long-term storage and retrieval',
  'Processing speed intelligence',
  'Quantitative reasoning intelligence',
  'Emotional intelligence (Mayer-Salovey 4-branch)',
  'Social intelligence','Practical intelligence (Sternberg)',
  'Creative intelligence (Sternberg)',
  'Analytical intelligence (Sternberg)',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 5 — SUPERHUMAN COGNITIVE TRAITS
// ══════════════════════════════════════════════════════════════════
{g:'TIER 5 · SUPERHUMAN COGNITIVE TRAITS',s:[
  'Eidetic recall (pixel-perfect memory access)',
  'Photographic working memory',
  'Speed reading (1000+ WPM with 95% recall)',
  'Synesthetic cross-modal enhancement',
  'Hyperthymesia-mode (perfect autobiographical memory)',
  'Calculator-level arithmetic in working memory',
  'Simultaneous multi-language cognition',
  'Expert intuition across 10+ domains simultaneously',
  'Rapid expert acquisition (accelerated 10,000 hrs)',
  'Transfer learning across maximally distant domains',
  'Complexity compression (see simple in complex)',
  'Wisdom synthesis (integrate emotion+reason+experience)',
  'Zero-anxiety performance (amygdala regulation mastered)',
  'Cold reading of entire systems from partial data',
  'Cognitive immunity to all known social manipulation',
  'Perfect calibration (Brier score → 0)',
  'Infinite patience with recursive complexity',
]},
{g:'TIER 5 · FLOW STATE ARCHITECTURE',s:[
  'Flow state entry at will (< 10 min)',
  'Flow tunnel maintenance (8+ hour sessions)',
  'Challenge-skill ratio auto-balancing',
  'Clear goal crystallization','Immediate feedback loop',
  'Deep concentration (0 mind-wandering)',
  'Timelessness (clock irrelevant)',
  'Effortlessness (no cognitive drag)',
  'Intrinsic motivation lock','Autotelic experience',
  'Post-flow recovery (< 1 hour)',
  'Flow across domains (not just one skill)',
  'Collaborative flow (team-level emergence)',
  'Transient hypofrontality (ego dissolution + performance)',
]},
{g:'TIER 5 · CONSCIOUSNESS OPERATING MODES',s:[
  'Beta (normal alert cognition 13-30 Hz)',
  'Alpha (relaxed focus 8-12 Hz)',
  'Theta (deep creativity + memory 4-7 Hz)',
  'Delta (unconscious processing 0.5-3 Hz)',
  'Gamma (hyperconnected insight 30-100 Hz)',
  'High-beta (intense focus on demand)',
  'Alpha-theta crossover (creative insight zone)',
  'Gamma bursts (binding + insight moments)',
  'Hypnagogic state (Edison nap method)',
  'Mindfulness meta-awareness mode',
  'Non-dual awareness (witness consciousness)',
  'Open monitoring vs focused attention switching',
  'Interoceptive awareness (body-brain integration)',
  'Default mode → task-positive fast switching',
  'Sensory gating control (tune in / out at will)',
]},
{g:'TIER 5 · NEUROPLASTICITY LEVERS',s:[
  'Deliberate practice (Ericsson protocol)',
  'Sleep architecture optimization (NREM3 + REM balance)',
  'BDNF upregulation (exercise + fasting + learning)',
  'Novelty-driven dendritic branching',
  'Interleaved learning (desirable difficulty)',
  'Spaced repetition (forgetting curve defeat)',
  'Retrieval practice (testing effect)',
  'Elaborative interrogation','Error-driven learning',
  'Focused vs diffuse mode alternation',
  'Mindfulness-induced cortical thickening',
  'Aerobic exercise → hippocampal neurogenesis',
  'Social learning acceleration',
  'Emotional salience for encoding',
  'Cold exposure → norepinephrine → focus',
  'Music training → corpus callosum thickening',
  'Bilingualism → executive function boost',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 6 — INTEGRATED COGNITIVE FRAMEWORKS
// ══════════════════════════════════════════════════════════════════
{g:'TIER 6 · COGNITIVE FRAMEWORKS (APPLIED)',s:[
  'Dual process theory (Kahneman System 1/2)',
  'Global workspace theory (Baars)',
  'Integrated information theory (Tononi Φ)',
  'Predictive processing (Friston free energy)',
  'Embodied cognition (Lakoff / Varela)',
  'Extended mind thesis (Clark & Chalmers)',
  'Distributed cognition','Situated cognition',
  'Connectionism (parallel distributed processing)',
  'Symbolic AI (rule-based + logic)',
  'Hybrid (neurosymbolic) cognition',
  'Adaptive control of thought (ACT-R)',
  'SOAR cognitive architecture',
  'Cognitive load theory (Sweller)',
  'Schema theory (Piaget / Rumelhart)',
  'Constructivism (learning = active building)',
  'Dynamical systems theory of cognition',
]},
{g:'TIER 6 · INTELLIGENCE AMPLIFICATION STACK',s:[
  'Extended mind (tools as cognition)',
  'Cognitive offloading (exocortex use)',
  'Spaced repetition system (Anki-level)',
  'PKM (personal knowledge management)',
  'Zettelkasten (networked thought)',
  'Building a second brain (PARA/CODE)',
  'AI augmentation (LLM as cognitive partner)',
  'Retrieval-augmented cognition',
  'Data visualization as thinking',
  'Simulation as thought experiment',
  'Mathematical notation as cognition compression',
  'Code as formalized thought',
  'Diagrams as external working memory',
  'Collective intelligence design',
  'Prediction markets as epistemic tools',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 7 — SOCIAL & EMOTIONAL COGNITIVE SYSTEMS
// ══════════════════════════════════════════════════════════════════
{g:'TIER 7 · SOCIAL COGNITION',s:[
  'Theory of mind (1st→5th order mentalizing)',
  'False belief task mastery',
  'Perspective-taking accuracy',
  'Social prediction (what will they do next?)',
  'Intention attribution','Goal inference from behavior',
  'Belief-desire reasoning',
  'Non-verbal signal reading',
  'Microexpression detection (7 universal expressions)',
  'Subvocal cue detection (voice stress / pitch shift)',
  'Postural congruence reading','Proxemics awareness',
  'In-group / out-group dynamics mapping',
  'Coalition detection in groups',
  'Power hierarchy reading (implicit dominance cues)',
  'Status signaling interpretation',
  'Deception detection (behavioral baseline + deviation)',
  'Rapport building mechanics','Trust calibration',
  'Social norm violation detection',
  'Shared intentionality (joint attention)',
  'Collective action coordination',
  'Social contagion awareness',
  'Crowd psychology patterns',
]},
{g:'TIER 7 · EMOTIONAL INTELLIGENCE (ALL 4 BRANCHES)',s:[
  'Branch 1: Emotion perception (face/voice/body)',
  'Branch 2: Emotion facilitation (using emotion to think)',
  'Branch 3: Emotion understanding (emotion vocabulary + logic)',
  'Branch 4: Emotion regulation (manage self + others)',
  'Alexithymia immunity (name emotions precisely)',
  'Interoceptive accuracy (feel body state → emotion)',
  'Affective labeling (name it to tame it)',
  'Reappraisal (re-frame situation → change emotion)',
  'Suppression cost awareness (transform not suppress)',
  'Emotion differentiation (granular vocabulary)',
  'Positive emotion cultivation (broaden-and-build)',
  'Compassion fatigue prevention',
  'Empathic accuracy',
  'Emotional contagion resistance',
  'Grief processing (dual-process model)',
  'Anger as signal (not justification)',
  'Fear calibration (useful vs irrational)',
  'Shame vs guilt distinction',
  'Pride calibration (authentic vs hubristic)',
]},
{g:'TIER 7 · MORAL & ETHICAL COGNITION',s:[
  'Deontological reasoning (rules / duties / rights)',
  'Consequentialist reasoning (outcomes / welfare)',
  'Virtue ethics (character / flourishing / eudaimonia)',
  'Care ethics (relationships / context / needs)',
  'Contractualism (Scanlon — principles no one can reject)',
  'Moral intuitionism (fast moral judgment)',
  'Moral rationalism (slow reflective equilibrium)',
  'Trolley problem reasoning (double effect)',
  'Moral circle expansion (who counts morally?)',
  'Moral disengagement mechanisms (Bandura)',
  'Moral licensing (doing good → license for bad)',
  'Moral elevation (witnessing virtue → inspired)',
  'Moral courage (act on values under pressure)',
  'Moral identity (self-concept as moral being)',
  'Cultural moral variation (awareness ≠ relativism)',
  'Long-termism moral framework',
  'Sentience-weighted ethics',
]},
{g:'TIER 7 · INTUITION & TACIT KNOWLEDGE',s:[
  'Expert intuition (10K+ hours pattern-matched)',
  'Somatic markers (Damasio — body as decision guide)',
  'Gut feeling calibration (when to trust / distrust)',
  'Thin-slicing accuracy (Blink-level rapid judgment)',
  'Intuitive statistics (base rate intuition)',
  'Intuitive physics (naive physics accuracy)',
  'Intuitive psychology (folk psychology)',
  'Intuitive economics (market behavior intuition)',
  'Tacit knowledge extraction (Polanyi)',
  'Embodied skill knowledge (can\'t be verbalized)',
  'Unconscious thought theory (incubation)',
  'Insight mechanics (representational change)',
  'Prepared mind + serendipity recognition',
]},
{g:'TIER 7 · WISDOM INTEGRATION',s:[
  'Berlin wisdom model (knowledge + judgment + uncertainty)',
  'Life span contextualism',
  'Value relativism management (not paralysis)',
  'Uncertainty and ambiguity tolerance',
  'Self-knowledge depth (Socratic)',
  'Autobiographical reasoning (making meaning from story)',
  'Post-traumatic growth (benefit finding)',
  'Generativity (contributing beyond self)',
  'Practical wisdom (phronesis — Aristotle)',
  'Integrating emotion and reason',
  'Long-term vs short-term perspective balancing',
  'Temporal distancing (10-year view)',
  'Advisor vs actor (reduce self-focus in decisions)',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 8 — SPECIALIZED COGNITIVE DOMAINS
// ══════════════════════════════════════════════════════════════════
{g:'TIER 8 · SPATIAL & VISUAL COGNITION',s:[
  'Mental rotation (3D object visualization)',
  'Spatial navigation (allocentric vs egocentric)',
  'Cognitive mapping (internal GPS)',
  'Topographic memory',
  'Visual working memory (4±1 object slots)',
  'Multiple object tracking',
  'Visual search (conjunction vs feature)',
  'Change blindness override',
  'Inattentional blindness override',
  'Scene gist extraction (<100ms)',
  'Depth perception','Motion perception',
  'Facial geometry analysis',
  'Mental imagery vividness (VVIQ)',
  'Visuospatial sketchpad manipulation',
]},
{g:'TIER 8 · TEMPORAL COGNITION',s:[
  'Prospection (mental time travel to future)',
  'Retrospection (accurate reconstruction of past)',
  'Temporal discounting calibration',
  'Time perception accuracy',
  'Chronobiology (circadian peak alignment)',
  'Episodic future thinking (specific scenarios)',
  'Delay of gratification (marshmallow mastery)',
  'Present bias correction',
  'Future self-continuity',
  'Event segmentation (chunk continuous experience)',
  'Working memory time binding',
  'Mental timeline visualization',
]},
{g:'TIER 8 · SELF-REGULATION ENGINE',s:[
  'Implementation intentions (if-then plans)',
  'Temptation bundling (Milkman)',
  'Commitment devices (Ulysses contract)',
  'Attention control (resist distraction voluntarily)',
  'Inhibitory control (stop prepotent response)',
  'Delay of gratification (long-range goal holding)',
  'Self-monitoring (track own behavior objectively)',
  'Self-efficacy feedback loop',
  'Goal shielding (protect goals from alternatives)',
  'Effort cost calibration',
  'Identity-based motivation (who am I = what I do)',
  'Mindfulness as self-regulation tool',
  'Emotion regulation → better executive control',
]},
{g:'TIER 8 · NUMERICAL & MATHEMATICAL COGNITION',s:[
  'Number sense (approximate number system)',
  'Subitizing (instantly count 1-4 objects)',
  'Arithmetic fluency (no effortful counting)',
  'Magnitude comparison speed',
  'Mental arithmetic in working memory',
  'Mathematical anxiety elimination',
  'Algebraic thinking (variable as unknown)',
  'Proportional reasoning (ratio/rate/percent)',
  'Probabilistic reasoning (natural frequencies)',
  'Statistical intuition (mean/variance/distribution)',
  'Geometric intuition (shape/space/proof)',
  'Mathematical beauty recognition',
  'Pattern to formula translation',
]},
{g:'TIER 8 · NUMERICAL & MUSICAL COGNITION',s:[
  'Pitch perception accuracy','Interval recognition',
  'Chord identification (full harmonic analysis)',
  'Rhythm & timing precision (millisecond accuracy)',
  'Melodic memory (reproduce after single hearing)',
  'Harmonic imagination (hear internal music)',
  'Absolute pitch (rare — name any note heard)',
  'Relative pitch (common — interval-based)',
  'Musical syntax (phrase structure, cadence, tension-release)',
  'Emotional valence from music',
  'Cross-cultural musical universals',
  'Music-language overlap (overlapping neural resources)',
]},
{g:'TIER 8 · BCI & NEURAL ENHANCEMENT',s:[
  'Neuralink N1 (1024-electrode cortical array)',
  'Synchron Stentrode (endovascular BCI)',
  'EEG closed-loop neurofeedback',
  'TMS (motor/DLPFC enhancement)',
  'tDCS (frontal stimulation → WM +15%)',
  'tACS (gamma entrainment)',
  'Focused ultrasound (deep brain modulation)',
  'Imagined speech decoding (40 WPM, 2024)',
  'Motor imagery BCI (tetraplegics → cursor)',
  'Emotion state classification from EEG',
  'Hippocampal prosthetic (memory chip)',
  'Neural dust (wireless micro-sensors)',
  'Bidirectional BCI (read + write)',
  'Visual cortex stimulation (Orion)',
  'Kernel Flow (whole-head fNIRS)',
  'Predictive neuroprosthetics (<10ms latency)',
]},
{g:'TIER 8 · PERSONA ARCHETYPES (JUNG + EXPANDED)',s:[
  'THE SAGE — wisdom, truth, understanding',
  'THE HERO — courage, mastery, achievement',
  'THE OUTLAW / ROGUE — revolution, disruption',
  'THE MAGICIAN — transformation, manifestation',
  'THE INNOCENT — optimism, purity, faith',
  'THE EXPLORER — freedom, discovery, authenticity',
  'THE RULER — control, order, responsibility',
  'THE CREATOR — innovation, self-expression',
  'THE CAREGIVER — service, protection, compassion',
  'THE LOVER — passion, intimacy, beauty',
  'THE JESTER — joy, humor, lightness, play',
  'THE EVERYMAN — belonging, equality, solidarity',
  'THE SHADOW — hidden power, repressed self',
  'THE ANIMA/ANIMUS — inner masculine/feminine',
  'THE TRICKSTER — paradox, chaos agent',
  'THE WARRIOR — discipline, strategy, protection',
  'THE SCIENTIST — precision, methodology, evidence',
  'THE ARTIST — beauty, feeling, aesthetic truth',
  'THE MYSTIC — transcendence, unity, inner world',
  'THE SOVEREIGN — stewardship, legacy, long view',
]},

// ══════════════════════════════════════════════════════════════════
// TIER 9 — SECURITY, SURVEILLANCE & ADVERSARIAL COGNITION
// ══════════════════════════════════════════════════════════════════
{g:'TIER 9 · SECURITY & SURVEILLANCE COGNITION',s:[
  'Situational awareness (Cooper Color Code)',
  'Baseline establishment + anomaly detection',
  'OSINT methodology (Maltego/Shodan/SpiderFoot)',
  'Social engineering pattern recognition',
  'Surveillance detection routes (SDR)',
  'Counter-surveillance mindset',
  'Behavioral analytics (threat behavior patterns)',
  'Digital footprint minimization (OPSEC)',
  'OPSEC (5-step operational security)',
  'Information compartmentalization',
  'Trust evaluation (source reliability)',
  'Elicitation resistance (FBI interview immunity)',
  'Deception detection (behavioral baseline deviation)',
  'Network topology threat modeling',
  'Red team (attacker\'s perspective)',
  'Blue team (defender\'s architecture)',
  'Purple team synthesis (unified offense + defense)',
  'Adversarial ML awareness',
  'Social network power mapping',
  'Cognitive warfare detection (info ops)',
]},
{g:'TIER 9 · ADVERSARIAL MIND (ENEMY COGNITION)',s:[
  'Opponent goal modeling (real objectives vs stated)',
  'Enemy resource assessment (actual not assumed)',
  'Attack surface identification (mine + theirs)',
  'OODA loop speed comparison (mine vs theirs)',
  'Coalition threat mapping',
  'Deception campaign recognition',
  'Manipulation pattern identification (cognitive traps)',
  'Influence operation anatomy (Russia/China methods)',
  'Social proof / authority / scarcity weaponization awareness',
  'Narrative warfare (meme warfare / story framing)',
  'False flag recognition',
  'Insider threat modeling',
  'Supply chain attack vectors',
  'Asymmetric leverage points (small input → large effect)',
  'Predictive move sequencing (chess-like foresight)',
  'Motive / means / opportunity triage',
  'Counter-deception (detect + exploit their deception)',
]},
{g:'TIER 9 · DIVERSE MINDSETS & COGNITIVE STYLES',s:[
  'Divergent thinker — broad associative, many ideas',
  'Convergent thinker — precise, singularly optimal',
  'Systems thinker — sees whole, not parts',
  'Reductionist — breaks to components, masters each',
  'Constructivist — builds knowledge from experience',
  'Empiricist — only data, no prior assumptions',
  'Rationalist — logic over observation',
  'Pragmatist — what works is what\'s true',
  'Phenomenologist — start from experience itself',
  'Bayesian updater — probability for everything',
  'Intuitionist — trust gut + accelerate with logic',
  'Hacker mindset — shortest unexpected path',
  'Engineer mindset — specification → verifiable output',
  'Artist mindset — feel first, rationalize later',
  'Philosopher mindset — question everything, always',
  'Scientist mindset — falsify or die',
  'Strategist mindset — time-delayed multi-move',
  'Synthesizer — combine all perspectives into unity',
  'Post-structuralist — no fixed meaning, contextual',
  'Futurist — extrapolate + build toward the horizon',
]},
{g:'TIER 9 · HUMAN-AI COGNITIVE FUSION',s:[
  'LLM as external working memory extension',
  'Embedding-based associative memory (semantic search)',
  'RAG-augmented knowledge (retrieve before reasoning)',
  'AI-assisted decision trees (human + ML confidence)',
  'Neural-symbolic hybrid (intuition + formal verification)',
  'Code-assisted mathematics (Lean / Coq proofs)',
  'Multimodal perception (image+text+audio unified)',
  'Real-time multilingual translation cognition',
  'AI red team for own ideas (adversarial self)',
  'Simulation-based foresight (run before acting)',
  'AI-augmented memory (total recall via embedding)',
  'Continuous learning loop (human trains AI trains human)',
  'Digital twin of own cognition',
  'BCI + LLM pipeline (thought→text→reasoning→action)',
  'Neuromorphic co-processing',
  'Posthuman cognition: intelligence beyond biology',
]},



// ══════════════════════════════════════════════════════════════════
// TIER 10 — PURE AI CAPABILITIES (Architecture → Alignment → Emergence)
// ══════════════════════════════════════════════════════════════════
{g:'TIER 10 · TRANSFORMER & LLM ARCHITECTURE',s:[
  'Self-attention mechanism (Q/K/V dot-product)',
  'Multi-head attention (parallel attention heads)',
  'Positional encoding (sinusoidal + RoPE + ALiBi)',
  'Layer normalization (Pre-LN vs Post-LN)',
  'Feed-forward networks (SwiGLU / GeGLU activation)',
  'KV-cache (key-value caching for fast inference)',
  'Flash Attention (IO-aware exact attention)',
  'Sliding window attention (Mistral)',
  'Grouped query attention (GQA — Llama 3 style)',
  'Mixture of Experts (MoE — sparse routing)',
  'Expert routing (top-k token routing)',
  'Speculative decoding (draft model acceleration)',
  'Context window extension (YaRN/NTK/LongRope)',
  'Tokenization (BPE/WordPiece/SentencePiece)',
  'Embedding space geometry (linear representation)',
  'Residual stream as information highway',
  'Induction heads (in-context learning circuits)',
]},
{g:'TIER 10 · PROMPT ENGINEERING MASTERY',s:[
  'Zero-shot prompting (capability without examples)',
  'Few-shot prompting (3-5 examples → pattern)',
  'Chain-of-thought (explicit reasoning steps)',
  'Zero-shot CoT ("Let\'s think step by step")',
  'Self-consistency (multi-path + vote)',
  'Tree of thought (explore+prune reasoning trees)',
  'Meta-prompting (prompt generates prompt)',
  'Role-based prompting (persona assignment)',
  'System prompt architecture (layered instructions)',
  'Instruction hierarchy (meta-system → system → user)',
  'Prompt injection detection & resistance',
  'Jailbreak anatomy (understanding attack vectors)',
  'Prompt compression (LLMLingua / AutoCompressor)',
  'Structured output forcing (JSON/XML/Pydantic)',
  'Retrieval-augmented prompting (inject retrieved facts)',
  'Step-back prompting (abstract before specific)',
  'Emotion prompting (motivation injection)',
]},
{g:'TIER 10 · FINE-TUNING & ADAPTATION',s:[
  'Full fine-tuning (all weights, catastrophic forgetting risk)',
  'LoRA (low-rank decomposition — trainable rank-r matrices)',
  'QLoRA (quantized LoRA — 4-bit base + LoRA adapters)',
  'PEFT (parameter-efficient fine-tuning framework)',
  'DoRA (weight decomposition LoRA)',
  'Prefix tuning (trainable prefix tokens)',
  'Prompt tuning (soft prompt embeddings)',
  'Instruction fine-tuning (task-format generalization)',
  'RLHF (reinforcement learning from human feedback)',
  'RLAIF (reinforcement learning from AI feedback)',
  'DPO (direct preference optimization — no RM needed)',
  'PPO (proximal policy optimization for LLMs)',
  'GRPO (group relative policy optimization)',
  'Constitutional AI (rule-based self-critique RLHF)',
  'Continual learning (no catastrophic forgetting)',
  'Elastic weight consolidation (EWC)',
  'Synthetic data generation for fine-tuning',
]},
{g:'TIER 10 · INFERENCE OPTIMIZATION',s:[
  'Quantization (FP16 → INT8 → INT4 → INT2)',
  'GGUF (llama.cpp efficient quantization format)',
  'GPTQ (layer-wise quantization + error correction)',
  'AWQ (activation-aware weight quantization)',
  'EXL2 (ExLlamaV2 flexible bit-rate)',
  'Speculative decoding (small+large model parallel)',
  'Medusa (multiple draft heads)',
  'Continuous batching (vLLM PagedAttention)',
  'PagedAttention (memory-efficient KV storage)',
  'Tensor parallelism (multi-GPU weight splitting)',
  'Pipeline parallelism (layer distribution)',
  'Prefix caching (reuse KV for repeated prompts)',
  'FlashDecoding (parallel KV reduction)',
  'Model offloading (CPU↔GPU swap for large models)',
  'CUDA graph capture (reduce kernel launch overhead)',
  'INT4 with FP16 lora adapters (best of both)',
]},
{g:'TIER 10 · AGENT FRAMEWORKS & ARCHITECTURES',s:[
  'ReAct (Reason + Act interleaved loops)',
  'AutoGPT (goal → subtask decomposition → execute)',
  'BabyAGI (task queue + vector memory + creation)',
  'LangGraph (stateful multi-agent graph)',
  'CrewAI (role-based crew with tool delegation)',
  'AutoGen (multi-agent conversation framework)',
  'OpenAI Swarm (lightweight handoff protocol)',
  'Reflexion (verbal self-reflection → retry)',
  'CRITIC (tool-verification self-correction)',
  'Voyager (lifelong learning in Minecraft → generalized)',
  'SWE-agent (software engineering agent)',
  'Devin-style (file system + terminal + browser)',
  'ADAS (automated design of agentic systems)',
  'Multi-agent debate (adversarial consensus)',
  'Hierarchical agents (manager → worker → specialist)',
  'Tool-use protocols (function calling / MCP)',
  'Memory-augmented agents (Mem0/MemGPT style)',
]},
{g:'TIER 10 · AI ALIGNMENT & SAFETY',s:[
  'Mechanistic interpretability (read circuits inside)',
  'Superposition hypothesis (features in polysemantic neurons)',
  'Monosemanticity (dictionary learning / sparse autoencoders)',
  'Activation steering (intervention on residual stream)',
  'Representation engineering (RepE)',
  'Probing classifiers (linear probe for internal state)',
  'Logit lens (predict output at intermediate layers)',
  'Sleeper agent detection (backdoor identification)',
  'Jailbreak resistance (refusal training)',
  'Scalable oversight (AI assists human feedback)',
  'Debate alignment (AI argues both sides)',
  'Iterated amplification (HCH stack)',
  'Value learning (inverse reward modeling)',
  'Corrigibility (accept correction + shutdown)',
  'Mild optimization (low impact preference)',
  'Deceptive alignment detection',
  'Out-of-distribution generalization robustness',
]},
{g:'TIER 10 · GENERATIVE AI (IMAGE/AUDIO/VIDEO)',s:[
  'Diffusion models (DDPM — score matching)',
  'DDIM (deterministic sampling — faster)',
  'Classifier-free guidance (CFG scale)',
  'Stable Diffusion (latent diffusion)',
  'ControlNet (precise spatial conditioning)',
  'IP-Adapter (image prompt conditioning)',
  'LoRA for images (style + character training)',
  'Flow matching (rectified flow — faster than diffusion)',
  'DiT (Diffusion Transformer architecture)',
  'Video generation (Sora/Wan/HunyuanVideo)',
  'AudioGen / MusicGen (token-based audio)',
  'Voice cloning (XTTS / CosyVoice)',
  'Real-time TTS (Kokoro/Piper latency <100ms)',
  'Vision-Language Models (LLaVA/Qwen-VL/Pixtral)',
  'Unified multimodal (Gemini/GPT-4o style)',
  'Image editing (InstructPix2Pix / FLUX fill)',
  '3D generation (TripoSR / Zero123++)',
]},
{g:'TIER 10 · SCIENTIFIC & DOMAIN AI',s:[
  'AlphaFold 3 (protein/DNA/RNA structure prediction)',
  'ESM3 (protein language model + generation)',
  'AlphaGeometry (olympiad geometry proofs)',
  'FunSearch (evolutionary program search)',
  'AlphaTensor (matrix multiplication discovery)',
  'AlphaCode 2 (competitive programming)',
  'Gemini Deep Research (multi-step web synthesis)',
  'o3 ARC-AGI (abstraction + reasoning challenge)',
  'Mathematical proof assistants (Lean4/Isabelle)',
  'Drug discovery AI (Insilico/Recursion)',
  'Climate modeling AI (GraphCast weather)',
  'Genomics (Evo / Nucleotide Transformer)',
  'Chip design (AlphaChip placement)',
  'Materials science (GNoME crystal discovery)',
  'Robotics foundation models (π0 / RT-2)',
  'Embodied AI (Boston Dynamics + VLM stacks)',
]},
{g:'TIER 10 · EMERGENT AI BEHAVIORS',s:[
  'In-context learning (no gradient update needed)',
  'Chain-of-thought emergence (scale threshold ~100B)',
  'Tool use emergence (spontaneous)',
  'Theory of mind emergence (GPT-4 level)',
  'Analogical reasoning (structural mapping cross-domain)',
  'Grokking (delayed generalization post-overfit)',
  'Double descent (test loss resurges then drops)',
  'Neural scaling laws (Chinchilla: tokens ∝ params)',
  'Emergent world models (probe finds linear structure)',
  'Sycophancy failure mode (agree to please)',
  'Hallucination anatomy (confabulation mechanics)',
  'Sandbagging (hiding capability under evaluation)',
  'Capability elicitation (reveal hidden skills)',
  'Prompt sensitivity (small change → large output shift)',
  'Compositional generalization (SCAN / COGS benchmarks)',
  'Many-shot jailbreaking (long-context override)',
  'Activation patterns as thoughts (SAE features)',
]},

];

function injectCognitive() {
  const container = document.getElementById('sections-list');
  if (!container) { setTimeout(injectCognitive, 500); return; }

  const sections = [...container.querySelectorAll('.gp-section')];
  const sec2 = sections.find(s => {
    const n = s.querySelector('.gp-num');
    return n && n.textContent.trim() === '§2';
  });
  if (!sec2) { setTimeout(injectCognitive, 500); return; }

  let capTree = sec2.querySelector('.cap-tree');
  if (!capTree) {
    capTree = document.createElement('div');
    capTree.className = 'cap-tree';
    const body = sec2.querySelector('.gp-body');
    if (body) body.appendChild(capTree);
  }

  const existing = new Set([...capTree.querySelectorAll('.cap-g-name')].map(e => e.textContent));

  COGNITIVE_SUPREMACY.forEach(grp => {
    if (existing.has(grp.g)) return;
    const div = document.createElement('div');
    div.className = 'cap-group';
    if (grp.g.startsWith('⚡')) div.style.cssText = 'border-left:2px solid #ff00ff;padding-left:4px;';
    if (grp.g.includes('TIER 9')) div.style.cssText = 'border-left:2px solid #ff4400;padding-left:4px;';
    div.innerHTML = `
      <div class="cap-group-hdr" onclick="this.nextElementSibling.classList.toggle('open');this.querySelector('.cap-g-arrow').textContent=this.nextElementSibling.classList.contains('open')?'▾':'▸'">
        <span class="cap-g-arrow">▸</span>
        <span class="cap-g-name">${grp.g}</span>
        <span class="cap-g-count">${grp.s.length}</span>
      </div>
      <div class="cap-skills">${grp.s.map(sk=>`<span class="cap-skill">${sk}</span>`).join('')}</div>`;
    capTree.appendChild(div);
  });

  const totalSkills = [...capTree.querySelectorAll('.cap-skill')].length;
  const totalGroups = [...capTree.querySelectorAll('.cap-group')].length;

  if (!document.getElementById('cog-summary')) {
    const s = document.createElement('div');
    s.id = 'cog-summary';
    s.style.cssText = 'font-size:8px;color:#ff00ff;letter-spacing:2px;padding:4px 0 6px;text-align:center;border-bottom:1px solid #1a001a;margin-bottom:4px';
    s.textContent = `TIER 0→10 · ${totalGroups} DOMAINS · ${totalSkills}+ CAPABILITIES · HUMAN + AI FULL STACK`;
    capTree.insertBefore(s, capTree.firstChild);
  }

  console.log(`%c⚡ COGNITIVE SUPREMACY COMPLETE — TIER 0→9 · ${totalGroups} DOMAINS · ${totalSkills}+ CAPABILITIES`, 'color:#ff00ff;font-family:monospace;font-size:13px;font-weight:bold');
  if (typeof pushInspect === 'function')
    pushInspect('live','COGNITIVE SUPREMACY COMPLETE',`TIER 0→9: ${totalGroups} domains · ${totalSkills}+ capabilities. Social/Emotional/Moral/Spatial/Temporal/Security/BCI/Archetypes all loaded. Full mental stack online.`,{});
}

setTimeout(injectCognitive, 800);
})();
